- project:
  name: openstack-dev/ci-sandbox
  check:
    jobs:
      - ci-sandbox-functional

- pipeline:
  name: check
  manager: independent
  trigger:
    gerrit:
      - event: patchset-created
      - event: comment-added
        comment: (?i)recheck
  success:
    gerrit:
      Verified: 1
  failure:
    gerrit:
      Verified: -1

